### PR TITLE
Allow names with more than one period

### PR DESCRIPTION
**Pull request by davisdude**
Allows files such as `Latitude_E7x70_1.17.5.exe`

### CODE REVIEW

**Comment by superm1** [comment]
Seems fine.  FYI, on modern machines such as E7x70 you can flash from the F12 menu or UEFI capsule.
https://www.dell.com/support/article/us/en/19/sln171755/updating-the-dell-bios-in-linux-and-ubuntu-environments?lang=en

**Comment by davisdude** [comment]
Yeah, that's what I ended up doing. Just figured I would submit the pull anyway in case somebody else needed it or came across it since it's still the recommended tool for flashing on the [Arch wiki](https://wiki.archlinux.org/index.php/Flashing_BIOS_from_Linux)

**Comment by superm1** [comment]
Ah OK.  If you can edit that wiki, would you mind referring people using Dell boxes to the URL I shared above?  Something like "Dell recommends Linux users flash their BIOS following information located here:".

**Comment by davisdude** [comment]
Got it (see [here](https://wiki.archlinux.org/index.php?title=Flashing_BIOS_from_Linux&type=revision&diff=496327&oldid=493779))

**Comment by superm1** [comment]
That's great, thanks!

**Pull request merged**
